### PR TITLE
add docker multiarch build

### LINKED ISSUE #712: create ARM based container
### What problem are you facing?
cannot execute the `quay.io/terraform-docs/terraform-docs` image on ARM based machines

### How could terraform-docs help solve your problem?

enhance [Dockerfile](https://github.com/terraform-docs/terraform-docs/blob/master/Dockerfile) to support ARM architecture

### PR DESCRIPTION
**Pull request by ganievs**
### Description of your changes
Add Docker multi-arch build

Fixes #712 

I have:

- [x] Read and followed terraform-docs' [contribution process].
- [x] All tests pass when I run `make test`.

### CODE REVIEW

**Comment by rickardp** [comment]
What is left for this to be merged?

**Comment by pascal-hofmann** [comment]
It looks like this changes the tags from `latest` to `latest-<arch>`, etc.

I think it would be nicer to push multi arch images with the existing tags instead.

**Comment by ganievs** [comment]
Hi @pascal-hofmann! The <arch> tag is specified a target architecture and it works seamlessly for the end user. You'll continue to pull in the same way by `image:tag` without an <arch> prefix

**Review by pascal-hofmann — COMMENTED** [review]
LGTM

**Review by pascal-hofmann — APPROVED** [review]

**Pull request merged**
