### PR TITLE
Add license header to codebase files

### PR DESCRIPTION
**Pull request by khos2ow**
Signed-off-by: Khosrow Moossavi <khos2ow@gmail.com>

### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [ ] This pull request adds a feature.
- [ ] This pull request enhances existing functionality.
- [ ] This pull request introduces breaking change.

For more information, see the [Contributing Guide](https://github.com/terraform-docs/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

~~Relicensing project from MIT to Apache 2.0 to be more compatible with rest of ecosystem.~~

After discussing with other folks, we've come to conclusion relicensing from MIT to Apache 2.0 is not worth it, and instead this PR only adds license header to all the files in the codebase.

### Issues Resolved

List any existing issues this pull request resolves.

### Checklist

Put an `x` into all boxes that apply:

- [ ] I have read the [Contributing Guidelines](https://github.com/terraform-docs/terraform-docs/tree/master/CONTRIBUTING.md).

#### Tests

- [ ] I have added tests to cover my changes.
- [ ] All tests pass when I run `make test`.

#### Documentation

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

#### Code Style

- [ ] My code follows the code style of this project.

### CODE REVIEW

**Comment by metmajer** [comment]
Apologies, @khos2ow I missed a review notification in my inbox... :(

**Comment by khos2ow** [comment]
@metmajer no worries, it's alright. I originally intended to relicense the project and really wanted your opinion on it. But after having a discussion with folks on Twitter I was convinced that was not a right move and reverted back the change and only added license header to files (i.e. a very mundane task without any implication)

**Comment by metmajer** [comment]
Like the approach. In case there is something urgent, please send an email directly, that will work better. Happy to help and share thoughts where needed.

**Comment by tbugfinder** [comment]
Hi @khos2ow,

could you briefly share what convinced you not to change the license?
I'd briefly read few resources and I understood that a change from MIT to APLv2 is possible (IANAL).

As you've added the Copyright header, contributions should maybe also provide a DCO and the PR bot should enforce it.


Thank You!

**Comment by khos2ow** [comment]
@tbugfinder you are correct in the assumption that changing from MIT to Apache 2.0 is pretty straightforward (in reality APL covers everything MIT has to offer), but, if only 1) you are the sole code owner or 2) all contributors have signed a CLA or 3) get a confirmation from *all* contributors to agree with this relicensing (MIT -> APL).

One way of getting that confirmation was through a CLA or DCO, which we didn't have until recently (#364). In other words if we had DCO enabled from the very beginning of the project, process of relicensing would have been just a PR to change the license without any extra paperwork needed.

Then, also, it comes to play how to handle the duality of licenses of files and codebase as a whole. MIT still requires the notice of the original license, so

- `LICENCE` file will need to contain both APL and MIT
- all new files will be licensed under APL
- old files remain under MIT until get modified, then will be dual licensed (i.e. dual header license)

All in all, it seemed cumbersome and was not really worth it to move from a permissive MIT to equally permissive Apache 2.0, just to only have a unified license with rest of the projects. You can read all the discussion and awesome suggestions folks made [in this thread](https://twitter.com/khos2ow/status/1354244132282265600) and [The Legal Side of Open Source](https://opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project).

**Pull request merged**
