### PR TITLE
Update/vulns

### PR DESCRIPTION
**Pull request by Aurelian-Shuttleworth**
### Description of your changes

As per [Issue721](https://github.com/terraform-docs/terraform-docs/issues/721) this is a minimal update to address multiple medium and high vulnerabilities detected by Snyk.

These issues need to be resolved as they block terraform docs use in many enterprises use cases.

Important to note, I also updated the Dockerfile as vulnerabilities were detected inside.

I have:

- [X] Read and followed terraform-docs' [contribution process].
- [X] All tests pass when I run `make test`.

### How has this code been tested

- Tested image in private CI pipelines
- ran `make test`
- tested image using `snyk container test`

If additional tests are required, please let me know.

[contribution process]: https://git.io/JtEzg

### CODE REVIEW

**Comment by Aurelian-Shuttleworth** [comment]
@khos2ow Could I get your eyes on this PR ^_^

**Review by khos2ow — APPROVED** [review]
Thank you @Aurelian-Shuttleworth!

**Comment by tbugfinder** [comment]
I guess fork

**Comment by floh96** [comment]
@khos2ow @metmajer Could you create a release please?

**Comment by tbugfinder** [comment]
and also add maintainers... ?

**Comment by khos2ow** [comment]
Sorry folks, a new release will be cut shortly!

**Pull request merged**
