### PR TITLE
Overhaul refactor of test suites

### LINKED ISSUE #410: Refactor test suites for ease of contribution
### What problem are you facing?

Currently if a contributor wants to change or add a functionality they would need to change massive number of `.golden` files in order to tests pass. This is really counterintuitive and redundant in most cases, it also causes a lot of conflicts when rebasing on main branch.

### How could terraform-docs help solve your problem?

Refactor test suites in a way that the target of each test function focuses on that particular area and eventually reduce blast radius of changes in tests.

### PR DESCRIPTION
**Pull request by khos2ow**
### Description of your changes

This PR refactors test suites and remove some of the redundant cases. Notable changes are:

- remove `NoXXX`, as they are redundant and already being tested with `OnlyXXX` tests
- move `SortByXXX` from each formatter to a common test file (these tests are shared among the different formats and does validate the ordering of items and doesn't need to be run for each individual format)
- move `HeaderFromXXXFile` from each formatter to a common test file.
- change the behavior of test to be "explicitly enabling a feature". For example all the `pretty` tests are converted to "no color" and one test is added to explicitly test "with color". 

Fixes #410

I have:

- [x] Read and followed terraform-docs' [contribution process].
- [x] All tests pass when I run `make test`.

### How has this code been tested

All the tests are passing with `make test`.

[contribution process]: https://git.io/JtEzg

### CODE REVIEW

**Comment by khos2ow** [comment]
@HeikoNeblung @nitrocode what do you think of these changes?

**Review by nitrocode — APPROVED** [review]

**Comment by nitrocode** [comment]
Impressive! Looks like this simplifies testing and makes contributing a lot easier. 😄 

Nice job!

Could you add some contributing docs too ?

**Comment by khos2ow** [comment]
> Could you add some contributing docs too ?

Would you elaborate a bit more of what, as an example, you would like to be added to help on this?

**Review by HeikoNeblung — APPROVED** [review]
Thank you @khos2ow LGTM. I think this will simplify testing for formaters a lot.
What do you think about additionally testing each formater behaviour with an empty terraform module. This will cover the last bit of each formater.

**Comment by nitrocode** [comment]
> Would you elaborate a bit more of what, as an example, you would like to be added to help on this?

Perhaps an addition to `CONTRIBUTING.md`?

**Comment by khos2ow** [comment]
@HeikoNeblung That's a very good point, I added new set of tests `HideAll` which targets `--hide-all` and modified `Empty` to mimic an empty module.

@nitrocode I also update `CONTRIBUTING.md`, would you please take a look to see if the intention is clear from contributor point of view? (specially put your #409 hat on!)

**Review by HeikoNeblung — APPROVED** [review]
LGTM

**Pull request merged**
