### PR TITLE
added tests for cli/config

### PR DESCRIPTION
**Pull request by HeikoNeblung**
### Description of your changes

added tests for cli/config to prevent issues like #387

I have:

- [x] Read and followed terraform-docs' [contribution process].
- [x] All tests pass when I run `make test`.

### How has this code been tested

successful run of make test

[contribution process]: https://git.io/JtEzg

### CODE REVIEW

**Comment by HeikoNeblung** [comment]
@khos2ow can you please KeePass this PR Open. After Dome additional research i'd like to add a test dir the cobra command.

**Comment by khos2ow** [comment]
Definitely, you can convert it to draft for now until it's ready. And thanks for the effort, it looks awesome 👍

**Comment by HeikoNeblung** [comment]
@khos2ow I've added some test cases for the cobra command. Do you think there are more cases needed, because these are mostly the same as the format tests.

**Comment by khos2ow** [comment]
I really like the idea of adding tests for `cmd/` commands in general, but it's a bit redundant with `internal/format` tests. But then again at the same time I've been thinking about refactoring `format` tests for a while now, mainly due to high percentage of conflict they impose on any single change on parallel PRs. To be honest I don't have an idea for it yet.

That being said I'll like to keep this PR around as a base for doing some experimentation and brainstorming for enhancing the test suites. I'll try to circle back to it shortly.

**Comment by khos2ow** [comment]
Please hold off any major work on testing until #410 is done.

**Comment by HeikoNeblung** [comment]
@khos2ow what do you think about a small function / script which generates the golden files? I‘ve created a SetExpected function testutil not committed yet) wich helps me in this particular case.

**Comment by khos2ow** [comment]
I originally thought about this, but this sounds more like of a chicken and egg problem. The script to generate golden files for test _is_ eventually the thing we want to test to make sure the intended output is generated properly from. #411 might solve most of the issues on this regard.

**Pull request closed without merging**
