### PR TITLE
Ignore inputs with terraform-docs-ignore comment

### PR DESCRIPTION
**Pull request by kampka**
### Description of your changes

In our monorepo projects, we often have a set of variables that is shared amongst modules, eg. a `tags` variable that is accepted by all modules in the repo. This is typically done by symlinking a `common-vars.tf` file into all modules in the repo. This leads to those documentation these inputs being generated on every modules documentation.
This is not only rather repetitive, it also clutters the documentation by mixing the module specific inputs with the common ones, making it harder to read the module docs.

This PR introduces the possibility to add a comment `# terraform-docs-ignore` to a variable, telling `terraform-docs` to ignore and not render the variable in the documentation. 

Example:
```hcl
# terraform-docs-ignore
variable "tags" {
  type        = map(string)
  default     = {}
  description = "A set of tags added to the resource."
}
```

Fixes: #680

I have:

- [x] Read and followed terraform-docs' [contribution process].
- [x] All tests pass when I run `make test`.

### How has this code been tested

The unit test shows that the variable tagged with `# terraform-docs-ignore` is not present after loading the module.

### CODE REVIEW

**Comment by Makeshift** [comment]
This is exactly what I needed for our repos, with exactly the same usecase. I'd really like to see this merged.

**Comment by khos2ow** [comment]
fixes #680

**Review by khos2ow — APPROVED** [review]
Thank you @kampka for the awesome work. I took the liberty to extend what you did for `variable` to the rest of the resources as well.

**Comment by kampka** [comment]
> Thank you @kampka for the awesome work. I took the liberty to extend what you did for `variable` to the rest of the resources as well.

Sure thing, glad this is helpful :+1:

**Pull request merged**
